name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Retrieve Secrets from Azure Key Vault
        id: get-secrets
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          CLIENT_ID=$(az keyvault secret show --name AZURE-CLIENT-ID --vault-name GordonITSolutionKV --query value -o tsv)
          CLIENT_SECRET=$(az keyvault secret show --name AZURE-CLIENT-SECRET --vault-name GordonITSolutionsKV --query value -o tsv)
          SUBSCRIPTION_ID=$(az keyvault secret show --name AZURE-SUBSCRIPTION-ID --vault-name GordonITSolutionsKV --query value -o tsv)
          TENANT_ID=$(az keyvault secret show --name AZURE-TENANT-ID --vault-name GordonITSolutionsKV --query value -o tsv)
          echo "::set-output name=client_id::$CLIENT_ID"
          echo "::set-output name=client_secret::$CLIENT_SECRET"
          echo "::set-output name=subscription_id::$SUBSCRIPTION_ID"
          echo "::set-output name=tenant_id::$TENANT_ID"
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ steps.get-secrets.outputs.client_id }}
          ARM_CLIENT_SECRET: ${{ steps.get-secrets.outputs.client_secret }}
          ARM_SUBSCRIPTION_ID: ${{ steps.get-secrets.outputs.subscription_id }}
          ARM_TENANT_ID: ${{ steps.get-secrets.outputs.tenant_id }}
